### ISSUE TITLE
Add new translate feature

### ISSUE THREAD

**Issue by hecris** [hecris/amigo#1]
## Implement a translation feature:
- command: `amigo translate <query>`
- gets translation from spanishdict.com/translate/(query)
- supports words AND phrases
### Don't forget to update 'Usage' in README.

**Comment by am2367** [comment]
@hecris After taking a look at this, it will not be as easy as it looks. Spanishdict offers no API, and a GET request to spanishdict.com/translate/(query) results in an HTML page response. A better option would be to use Google's Translation API. https://cloud.google.com/translate/docs/reference/translate

If this is acceptable to you, I would be happy to create the feature.

**Comment by hecris** [comment]
@am2367 Sure! There is a [Google Translate python library](https://pypi.org/project/googletrans/) that I suggest. Nonetheless, the choice is yours! :+1: 
Don't forget to add yourself to the Contributors section.

**Comment by am2367** [comment]
@hecris I've forked it and added the required code but I cannot test anything. I imported this click library that you use and tried running amigo from the cli in multiple ways and it doesn't work. "python amigo.py conjugate ser" works but doesn't output anything.

**Comment by hecris** [comment]
@am2367 make sure to run the follow command in the repo folder (virtualenv is recommended)
`pip install --editable .`
afterwards, try in the command line `amigo conjugate ser`

**Comment by am2367** [comment]
@hecris pip install --editable requires 1 argument.

**Comment by hecris** [comment]
@am2367 don't forget the period. It represents the current directory :+1: 
`pip install --editable .`

**Comment by am2367** [comment]
@hecris Got the following error "The system cannot find the file specified: 'c:\\program files (x86)\\python36-32\\lib\\site-packages\\amigo-1.0-py3.6.egg'"

**Comment by hecris** [comment]
@am2367 try this:
1. Go to the folder where the project is.
2. I assume you're on windows. Press Shift and Right Click together. Click 'Open Command window here' from the menu.
3. run the following command `pip install --editable .`

**Comment by am2367** [comment]
@hecris that worked. Will test my code and make a pull request shortly.

**Comment by am2367** [comment]
@hecris Just made a pull request. Make sure to read the comments I made on it. Lmk if you have questions or need me to change something.

**Comment by hecris** [comment]
Thank you for the contribution @am2367 ! I will review the code and merge the pull if all works well.

**Comment by am2367** [comment]
@hecris No problem. Do make sure to follow the steps to clone that repo and install the required files. I wasn't sure how to add a repo with a setup.py file in to your setup.py file.

**Comment by hecris** [comment]
It works! Thanks for the contribution. If you want, you can add yourself to Contributors section and submit another PR.
