### ISSUE TITLE
Add new testme feature

### ISSUE THREAD

**Issue by hecris** [hecris/amigo#2]
## Implement a testme feature
- command: `amigo testme --english --spanish`
- this will return a phrase in either english or spanish. the user will be prompted to translate the phrase. if they get it right, congratulate them!
## Don't forget to update 'Usage' in README

**Comment by edenriquez** [comment]
can i take this ? ✋ @hecris

**Comment by hecris** [comment]
You got it. :+1: 

EDIT: Other people can work on this!
