### ISSUE TITLE
Update setup.py

### ISSUE THREAD

**Issue by hecris** [hecris/amigo#7]
**please refer to PR #4**
amigo currently uses the following package: https://github.com/BoseCorp/py-googletrans
It is a fork that fixes a bug in the [original py-googletrans](https://pypi.org/project/googletrans/).
Submit a PR that updates setup.py accordingly.
**Your pull request should merge your branch with hecris:translate_feature branch**

**Comment by ericm** [comment]
Ok, I can do that. Assign me this.

**Comment by hecris** [comment]
Sure, you got it :+1:

**Comment by ericm** [comment]
#8
